# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantlocation_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
